// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvpeurrprccfmvorlqkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2cGV1cnJwcmNjZm12b3JscWt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMDU0NDQsImV4cCI6MjA2ODg4MTQ0NH0.r8Kt9MJVIYhkK98_ZLs6_fQmiuEA-LwyGRZj-8yexBM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});